import * as vite from "vite"
import react from "@vitejs/plugin-react"
import tailwindcss from "@tailwindcss/vite"
import {ProjectModel, WebappConfig} from "./ProjectModel"
import fs from "node:fs"

export function viteCommonConfig(webapp: WebappConfig) {

  // FIXME - only use this for the dev server
  const injectPageContextPlugin = (): vite.Plugin => {
    const plugin: vite.Plugin = {
      name: "inject-page-context-plugin",
      apply: "serve",
      configureServer: (server: vite.ViteDevServer) => {
        server.middlewares.use(async (req, res, next) => {
          if (
            req.url?.startsWith("/") &&
            req.headers.accept?.includes("text/html")
          ) {
            // FIXME - generate the html
            const lines = [
              `<!doctype html>`,
              `<html lang="en">`,
              `  <head>`,
              `    <!-- FIXME - SHOULD BE GENERATED BY THE APP -->`,
              `    <meta charset="UTF-8" />`,
              `    <link rel="icon" type="image/svg+xml" href="/sampleIcon.svg" />`,
              `    <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
              `    <title>what</title>`,
              `  </head>`,
              `  <body>`,
              `    <div id="root"></div>`,
              `    <script type="module" src="/app/main.tsx"></script>`,
              `  </body>`,
              `</html>`,
            ]
            const htmlText = lines.join("\n")
            
            const transformedIndexHtml = await server.transformIndexHtml(
              req.url,
              htmlText,
            )
            res.setHeader("Content-Type", "text/html")
            res.end(transformedIndexHtml)
          } else {
            next()
          }
        })
      },
    }
    return plugin
  }

  return {
    // Where index.html is located
    root: webapp.viteProjectRoot,
    base: webapp.devServerBase,
    plugins: [
      // Among other things, this makes sure "React" is defined
      // everywhere
      react(),
      tailwindcss(),
      injectPageContextPlugin(),
    ],
  }
}
